### ISSUE TITLE
My employee will love this access noname

### ISSUE THREAD

**Issue by McWifiYt** [AquamarineMiiverseTeam/Aquamarine-Offdevice#4]
![image](https://github.com/AquamarineMiiverseTeam/Aquamarine-Offdevice/assets/88051764/f2560c2b-003e-4ab5-9c2c-f8e6493b8850)

**Comment by NoNameGivenCoder** [comment]
Aquamarine is public and live, not sure how this is an issue?

**Comment by McWifiYt** [comment]
The issue is im omey and my employee will love the web access even though its buggy mess so ddos soon???

**Comment by NoNameGivenCoder** [comment]
I honestly could not care less that you’re Omey, nor your employee.
