### ISSUE TITLE
My name is David sosa, and i look like Nikocado Avocado, and the reasons below are why i dont get any bitches

### ISSUE THREAD

**Issue by McWifiYt** [AquamarineMiiverseTeam/Aquamarine-Offdevice#5]
![image](https://github.com/AquamarineMiiverseTeam/Aquamarine-Offdevice/assets/88051764/37eb3d3a-3a50-47c8-9d20-19560ba5c7b7)
FIX THE WEBSITE POSTINGS

**Comment by davidsosa2022** [comment]
![image](https://github.com/AquamarineMiiverseTeam/Aquamarine-Offdevice/assets/118952873/f7ebff9f-a063-4332-8cac-e6c8ec4d49f1)
this u man

**Comment by McWifiYt** [comment]
LMAO ANYWAYS IMORA IS POSTING ON AQUAMARINE WITH BEST MESSAGE
![image](https://github.com/AquamarineMiiverseTeam/Aquamarine-Offdevice/assets/88051764/70f4c05d-cc6b-4197-8f81-b484873e7bd2)

**Comment by McWifiYt** [comment]
r.i.p https://portal.olv.aquamarine.lol/

**Comment by sexyfishy** [comment]
you're literally built like a brown sugar pop tart bro shut up

**Comment by BradenYes** [comment]
omey what's your address fr fr

**Comment by McWifiYt** [comment]
its 123 street st

**Comment by BradenYes** [comment]
Go to bed, Zachery. It's 7 PM.
